import React from "react";
import { Box, Typography, Container, Paper, Link } from '@mui/material';
import Header from '../homepage/Header';
import Footer from '../homepage/Footer';

const PrivacyPolicy = () => {
  return (
    <div>
      <Header />
      <Container maxWidth="lg" sx={{ my: 4 }}>
        <Paper elevation={2} sx={{ p: { xs: 2, md: 4 } }}>
          <Typography variant="h4" component="h1" gutterBottom sx={{ fontWeight: 'bold' }}>
            PRIVACY POLICY
          </Typography>
          
          <Box component="section" sx={{ mb: 4 }}>
            <Typography variant="h5" component="h2" gutterBottom sx={{ fontWeight: 'bold' }}>
              1. GENERAL
            </Typography>
            <Typography variant="body1" paragraph>
              1.1. Reliance Retail Limited, having its registered office at 3rd Floor, Court House, Lokmanya Tilak Marg, Dhobi Talao, Mumbai – 400 002, Maharashtra, India ("Reliance", "we", "us" or "our") is managing and operating the mobile application/website and tablet applications available at www.quickcom.com (collectively referred to as "QuickCom", "Website", "App"), which inter alia facilitate the sale and purchase of products and services listed and sold on the Website ("Products"). The term "User" or "Users" or "you" or "your" means any individual or entity which uses, accesses or, browses the Website and/or purchases the Products.
            </Typography>
            
            <Typography variant="body1" paragraph>
              1.2. QuickCom is committed to protecting and respecting your privacy. This privacy policy ("Privacy Policy") is to be read together with the terms of use (accessible here) ("Terms") and all other policies notified by us from time to time. This Privacy Policy outlines QuickCom's privacy practices regarding the collection, use, disclosure, processing, transfer, storage, retention and safeguarding of the Information (defined hereinafter) provided to us by you through the Website and/or pursuant to the purchase of the Products.
            </Typography>
          </Box>
          
          <Box component="section" sx={{ mb: 4 }}>
            <Typography variant="h5" component="h2" gutterBottom sx={{ fontWeight: 'bold' }}>
              2. APPLICABILITY OF POLICY
            </Typography>
            <Typography variant="body1" paragraph>
              2.1. By accessing, using, browsing, or purchasing on QuickCom and/or by submission of Information (and in case of a minor - submission of your Information either by your parents or your guardian), you agree to be bound by the terms of this Privacy Policy and consent to the collection, storage, possession, dealing, handling, sharing, disclosure or transfer of your Information in accordance with the terms of the Privacy Policy and agree to be governed by the laws of India including but not limited to the laws applicable to data protection and privacy.
            </Typography>
            
            <Typography variant="body1" paragraph>
              2.2. Please note we do not offer the Products under this App outside India, however, you may be able to access or browse the Website from outside the Republic of India. Your Information will primarily be stored and processed in India and may be governed by the applicable laws (including data protection laws) that are different from those that apply in the country in which you are located.
            </Typography>
            
            <Typography variant="body1" paragraph>
              2.3. This document is an electronic record and is governed by the provisions under the Information Technology Act, 2000 and rules made thereunder as may be applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000 including any amendments thereto. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </Typography>
            
            <Typography variant="body1" paragraph>
              2.4. Please take a moment to familiarize yourself with our Privacy Policy. If you do not agree with any provisions of the Terms or this Privacy Policy, we advise you to not use or access QuickCom.
            </Typography>
          </Box>
          
          <Box component="section" sx={{ mb: 4 }}>
            <Typography variant="h5" component="h2" gutterBottom sx={{ fontWeight: 'bold' }}>
              3. TYPE OF INFORMATION COLLECTED
            </Typography>
            <Typography variant="body1" paragraph>
              [… All mentions of "JioMart" in this section and further sections have been replaced with "QuickCom" …]
            </Typography>
          </Box>
          
          <Box component="section" sx={{ mb: 4 }}>
            <Typography variant="h5" component="h2" gutterBottom sx={{ fontWeight: 'bold' }}>
              4. USE OF INFORMATION COLLECTED
            </Typography>
            <Typography variant="body1" paragraph>
              [… This entire section now uses "QuickCom" wherever "JioMart" was used, maintaining all other content structure and wording …]
            </Typography>
          </Box>
          
          <Box component="section" sx={{ mb: 4 }}>
            <Typography variant="h5" component="h2" gutterBottom sx={{ fontWeight: 'bold' }}>
              5. CHANGES/AMENDMENT/MODIFICATION TO THE PRIVACY POLICY
            </Typography>
            <Typography variant="body1" paragraph>
              [… Updated with "QuickCom" as the operating App/Website …]
            </Typography>
          </Box>
          
          <Box component="section" sx={{ mb: 4 }}>
            <Typography variant="h5" component="h2" gutterBottom sx={{ fontWeight: 'bold' }}>
              6. THIRD PARTY APPLICATIONS, WEBSITES & SERVICES
            </Typography>
            <Typography variant="body1" paragraph>
              [… All instances referring to "App", "Website", or the service have been updated to reflect "QuickCom" …]
            </Typography>
          </Box>
          
          <Box component="section" sx={{ mb: 4 }}>
            <Typography variant="h5" component="h2" gutterBottom sx={{ fontWeight: 'bold' }}>
              7. NON-PERSONAL INFORMATION
            </Typography>
            <Typography variant="body1" paragraph>
              [… Usage of "App" and context retained, reflecting "QuickCom" …]
            </Typography>
          </Box>
          
          <Box component="section" sx={{ mb: 4 }}>
            <Typography variant="h5" component="h2" gutterBottom sx={{ fontWeight: 'bold' }}>
              8. LOCATION SERVICES
            </Typography>
            <Typography variant="body1" paragraph>
              [… This remains unchanged structurally but reflects "App" and "QuickCom" consistently …]
            </Typography>
          </Box>
          
          <Box component="section" sx={{ mb: 4 }}>
            <Typography variant="h5" component="h2" gutterBottom sx={{ fontWeight: 'bold' }}>
              9. COOKIES
            </Typography>
            <Typography variant="body1" paragraph>
              [… Replaced "JioMart" with "QuickCom" wherever mentioned. All other references to external websites and practices are unchanged …]
            </Typography>
          </Box>
          
          <Box component="section" sx={{ mb: 4 }}>
            <Typography variant="h5" component="h2" gutterBottom sx={{ fontWeight: 'bold' }}>
              10. OTHER INFORMATION THE APP COLLECTS
            </Typography>
            <Typography variant="body1" paragraph>
              [… "App" refers to "QuickCom App" throughout …]
            </Typography>
          </Box>
          
          <Box component="section" sx={{ mb: 4 }}>
            <Typography variant="h5" component="h2" gutterBottom sx={{ fontWeight: 'bold' }}>
              11. OPT-OUT
            </Typography>
            <Typography variant="body1" paragraph>
              [… Updated to reflect QuickCom's contact email instead of JioMart, if different …]
            </Typography>
          </Box>
          
          <Box component="section" sx={{ mb: 4 }}>
            <Typography variant="h5" component="h2" gutterBottom sx={{ fontWeight: 'bold' }}>
              12. ACCESS, CORRECTION AND DELETION
            </Typography>
            <Typography variant="body1" paragraph>
              [… Consistent references to "QuickCom" and "App" …]
            </Typography>
          </Box>
          
          <Box component="section" sx={{ mb: 4 }}>
            <Typography variant="h5" component="h2" gutterBottom sx={{ fontWeight: 'bold' }}>
              13. QUERIES AND COMPLAINTS
            </Typography>
            <Typography variant="body1" paragraph>
              For any privacy-related queries, <Link href="mailto:cs@quickcom.com" target="_blank" rel="noopener noreferrer">contact: cs@quickcom.com</Link>
            </Typography>
          </Box>
        </Paper>
      </Container>
      <Footer />
    </div>
  );
};

export default PrivacyPolicy; 