import React from 'react';
import { Box, Typography, Container, Paper, Link   } from '@mui/material';
import Header from '../homepage/Header';
import Footer from '../homepage/Footer';

export default function TermsAndConditions() {
  return (
    <div>
    <Header />
    <Container maxWidth="lg" sx={{ my: 4 }}>
      <Paper elevation={2} sx={{ p: { xs: 2, md: 4 } }}>
        <Typography variant="h4" component="h1" gutterBottom sx={{ fontWeight: 'bold' }}>
          TERMS AND CONDITIONS FOR USE OF QUICKCOM
        </Typography>
        
        <Typography variant="body1" paragraph>
          Welcome to QuickCom!
        </Typography>
        
        <Typography variant="body1" paragraph>
          The portal <Link href="http://localhost:3000/homepage" target="_blank" rel="noopener noreferrer">www.quickcom.com</Link> and its corresponding mobile application (collectively, "QuickCom"), 
          is managed and operated by Reliance Retail Limited ("Reliance", "we", "us" or "our"). 
          Any natural or legal person who accesses and/or uses QuickCom in any manner ("you" or "your") 
          or uses any current or future service or functionality or offer made available on QuickCom ("Service") 
          will be subject to these terms and conditions for use of QuickCom ("Terms of Use"), as updated from time 
          to time and such terms, guidelines and conditions as may be applicable to such Service ("Service Terms"). 
          If these Terms of Use are inconsistent with such Service Terms, the Service Terms will control to the 
          extent of such inconsistency with respect to the applicable Service.
        </Typography>
        
        <Typography variant="body1" paragraph>
          These Terms of Use constitute an electronic record within the meaning of the applicable law. 
          This electronic record is generated by a computer system and does not require any physical or 
          digital signatures. Please read these Terms of Use carefully before using or accessing QuickCom 
          or availing any Service. By using QuickCom or availing any Service, you signify your agreement 
          to be bound by these Terms of Use.
        </Typography>
      </Paper>
    </Container>
    <Footer />
    </div>
  );
} 